version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - PHP_V=${PHP_V}
    container_name: app-${APP_NAME}
    restart: always
    working_dir: /var/www/
    volumes:
      - /srv/www/${APP_NAME}:/var/www

  nginx:
    image: nginx:1.24-alpine
    container_name: nginx-${APP_NAME}
    restart: always
    ports:
      - ${PORT}:80
    volumes:
      - /srv/www/${APP_NAME}:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

networks:
  network-${APP_NAME}:
    external: true
