[program:laravel-npm-dev]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www
command=npm run dev
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/laravel-npm-dev.log